# Generated by Django 5.0.6 on 2024-09-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jpeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourtext', models.TextField(max_length=5000)),
                ('fileup', models.FileField(default=None, max_length=250, null=True, upload_to='Jpeople/')),
            ],
        ),
    ]
