# Generated by Django 5.0.6 on 2024-09-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobblogs', '0002_alter_jobblogs_jobpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobblogs',
            name='jobpost',
            field=models.CharField(max_length=900),
        ),
    ]
